// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1dC3Wk5fg4ddmk0pBhBpoucJ-IJdgr48',
    appId: '1:539344127866:web:55cf202d472ce5665178c3',
    messagingSenderId: '539344127866',
    projectId: 'real-estate-58f0f',
    authDomain: 'real-estate-58f0f.firebaseapp.com',
    storageBucket: 'real-estate-58f0f.firebasestorage.app',
    measurementId: 'G-YBMKPPK8J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjcttE_jPBo2MK7rhSaO7SvhBIArqgJ_Q',
    appId: '1:539344127866:android:562bc4a1c91bf34b5178c3',
    messagingSenderId: '539344127866',
    projectId: 'real-estate-58f0f',
    storageBucket: 'real-estate-58f0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYjjrGRhbSZluBxpoXXaZ48gwM082Yois',
    appId: '1:539344127866:ios:8edd981992092f3a5178c3',
    messagingSenderId: '539344127866',
    projectId: 'real-estate-58f0f',
    storageBucket: 'real-estate-58f0f.firebasestorage.app',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYjjrGRhbSZluBxpoXXaZ48gwM082Yois',
    appId: '1:539344127866:ios:8edd981992092f3a5178c3',
    messagingSenderId: '539344127866',
    projectId: 'real-estate-58f0f',
    storageBucket: 'real-estate-58f0f.firebasestorage.app',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1dC3Wk5fg4ddmk0pBhBpoucJ-IJdgr48',
    appId: '1:539344127866:web:27bb41b4fbab47835178c3',
    messagingSenderId: '539344127866',
    projectId: 'real-estate-58f0f',
    authDomain: 'real-estate-58f0f.firebaseapp.com',
    storageBucket: 'real-estate-58f0f.firebasestorage.app',
    measurementId: 'G-C2G54L93BE',
  );
}
